version: '3.4'

services:
  ordering:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

