version: '3.4'

services:
  ordering:
    image: ordering
    build:
      context: .
      dockerfile: Ordering/Dockerfile

  ordering-api:
    image: orderingapi
    build:
      context: .
      dockerfile: Ordering-Api/Dockerfile

